TebLocalPlannerROS:

 EBandPlannerROS:

  eband_internal_force_gain: 1.0
  eband_external_force_gain: 0.32

  Ctrl_rate : 15

  differenrial_drive: False
  
  #Set the acceleration limits of the robot
  max_acceleration: 0.8
  virtual_mass: 0.75
  max_translational_acceleration: 0.5
  max_rotational_acceleration: 0.1  #Ali tested

  #Set the velocity limits of the robot
  max_vel_lin: 1.6
  max_vel_th: 0.1
  min_vel_lin: 0.1
  min_vel_th: 0.0
  min_in_place_vel_th: 0.0
  in_place_trans_vel: 0.0  

  rotation_correction_threshold: 0.2 #Ali Tested - Don't change 