footprint: [[0.10, 0.05], [-0.10, 0.05], [-0.10, -0.05], [0.10, -0.05]]
inflation_radius: 0.01
transform_tolerance: 1

raytrace_range: 12.5

plugins: 
  - {name: obstacles,        type: "costmap_2d::VoxelLayer"}

obstacles:
  observation_sources: lidar
  
  lidar: {sensor_frame: base_link, data_type: PointCloud2, topic: /lidar/output, marking: true, clearing: true}
  #zed: {sensor_frame: base_link, data_type: PointCloud2, topic: /zed/output, marking: true, clearing: true}
