global_costmap:
  global_frame: base_link
  robot_base_frame: base_link
  update_frequency: 10.0
  publish_frequency: 2.0
  width: 40.0
  height: 40.0
  origin_x: -20
  origin_y: -20
  resolution: 0.1
  obstacle_range: 18.0
