TrajectoryPlannerROS:

  max_vel_x: 2.0
  min_vel_x: 0.5
  max_vel_theta: 1.0
  min_vel_theta: -1.0

  min_in_place_rotational_vel: 1.2
  min_in_place_vel_theta: 0.4

  acc_lim_x: 2.5
  acc_lim_y: 2.5
  acc_lim_theta: 3.2

  escape_vel: -0.5
  
  holonomic_robot: false

  meter_scoring: true

  path_distance_bias: 0.6
  goal_distance_bias: 0.8
  occdist_scale: 0.01

  ##################################

  #oscillation_reset_dist: 0.05
  #publish_cost_grid_pc: false

  #prune_plan: true

  #sim_time: 1.5
  #sim_granularity: 0.025
  #angular_sim_granularity: 0.025
  #vx_samples: 8
  #vtheta_samples: 20

  #dwa: true
  #simple_attractor: false

  #yaw_goal_tolerance: 0.1 # about 6 degrees
  #xy_goal_tolerance: 0.2  # 20 cm
  #latch_xy_goal_tolerance: false

  #heading_lookahead: 1.0
  #heading_scoring: false
  #heading_scoring_timestep: 0.8


  
  
  
  

  


