local_costmap:
  global_frame: base_link
  robot_base_frame: base_link
  update_frequency: 10.0
  publish_frequency: 2.0
  rolling_window: true
  width: 8.0
  height: 8.0
  origin_x: -4.0
  origin_y: -4.0
  resolution: 0.1
  obstacle_range: 3.1
