

global_frame: base_link
robot_base_frame: base_link
update_frequency: 10.0
publish_frequency: 5.0
width: 100.0
height: 100.0
#rolling_window: true
origin_x: -5.0
origin_y: -5.0
resolution: 0.1
obstacle_range: 20.0

plugins:
- {name: lidar_layer,          type: "costmap_2d::VoxelLayer"}
- {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
